name: table_note
description: Genel amaçlı tablo not alma uygulaması

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/table_note_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/table_note_icon.png
